openapi: 3.0.4

info:
  title: Paved Way API
  description: API per la gestione degli eventi sulla mobilità della città di Trento.
  version: 1.0.0

servers:
  - url: TODO

paths:
  /reports:
    get:
      summary: Restituisce la lista delle segnalazioni.
      description: Restituisce la lista delle segnalazioni.
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: Numero di segnalazioni da saltare prima di restituire i risultati.
        - in: query
          name: limit
          schema:
            type: integer
          description: Numero massimo di segnalazioni da restituire.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Report"
        "500":
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /sites:
    get:
      summary: Restituisce la lista dei cantieri esistenti.
      description: Restituisce la lista dei cantieri esistenti.
      parameters:
        - in: query
          name: offset
          schema:
            type: integer
          description: Numero di segnalazioni da saltare prima di restituire i risultati.
        - in: query
          name: limit
          schema:
            type: integer
          description: Numero massimo di cantieri da restituire.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Site"
        "500":
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommonError"
    post:
      summary: Crea un nuovo cantiere.
      description: Crea un nuovo cantiere. Per creare un cantiere è necessario essere autenticati come amministratore.
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Site"
      responses:
        "201":
          description: Cantiere creato con successo.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Site"
        "400":
          description: Richiesta non valida.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Non autorizzato. Devi fornire una chiave API valida.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Accesso negato. Devi essere un amministratore per creare un cantiere.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Errore interno del server.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      description: >-
        Chiave API per l'autenticazione.
        Deve essere fornita nell'intestazione della richiesta.
        Deve essere un token JWT valido.

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Messaggio di errore.
        code:
          type: integer
          description: Codice di errore.
        message:
          type: string
          description: Messaggio di errore dettagliato.

    Location:
      type: object
      required:
        - latitude
        - longitude
        - street
        - number
        - city
        - code
      properties:
        latitude:
          type: number
          format: float
          description: Latitudine della posizione.
          minimum: -90
          maximum: 90
        longitude:
          type: number
          format: float
          description: Longitudine della posizione.
          minimum: -180
          maximum: 180
        street:
          type: string
          description: Nome della strada.
        number:
          type: string
          description: Numero civico.
        city:
          type: string
          description: Nome della città.
        code:
          type: string
          description: Codice di Avviamento Postale.
          minLength: 5
          maxLength: 5

    Duration:
      type: object
      required:
        - start
      properties:
        start:
          type: string
          format: date-time
          description: Data e ora di inizio dell'evento.
        end:
          type: string
          format: date-time
          description: Data e ora di fine dell'evento.

    Comment:
      type: object
      required:
        - userId
        - text
      properties:
        id:
          type: integer
          description: ID del commento (generato automaticamente dal server).
        userId:
          type: integer
          description: ID dell'utente che ha scritto il commento.
        text:
          type: string
          description: Testo del commento.
        createdAt:
          type: string
          format: date-time
          description: Data e ora di creazione del commento.

    Event:
      type: object
      required:
        - eventType
        - name
        - info
        - location
        - duration
      properties:
        id:
          type: integer
          description: ID dell'evento (generato automaticamente dal server).
        eventType:
          type: string
          enum:
            - report
            - site
          description: Tipo di evento.
        name:
          type: string
          description: Nome dell'evento.
        info:
          type: string
          description: Descrizione dell'evento.
        location:
          $ref: "#/components/schemas/Location"
          description: Posizione dell'evento.
        duration:
          $ref: "#/components/schemas/Duration"
          description: Durata dell'evento.
        createdAt:
          type: string
          format: date-time
          description: Data e ora di creazione dell'evento (ora attuale se non specificata).
        comments:
          type: array
          items:
            $ref: "#/components/schemas/Comment"
          description: Lista dei commenti associati all'evento.
        discriminator:
          propertyName: eventType

    Report:
      allof:
        - $ref: "#/components/schemas/Event"
        - type: object
          required:
            - createdBy
            - rating
            - status
          properties:
            createdBy:
              type: integer
              description: ID dell'utente che ha creato la segnalazione.
            photos:
              type: array
              items:
                type: string
                format: binary
              description: Lista delle foto associate alla segnalazione.
            rating:
              type: integer
              description: Punteggio della segnalazione.
            status:
              type: string
              enum:
                - pending
                - approved
                - rejected
              description: Stato della segnalazione.

    Site:
      allof:
        - $ref: "#/components/schemas/Event"
        - type: object
          required:
            - companyName
          properties:
            companyName: 
              type: string
              description: Nome dell'impresa edile che sta lavorando sul cantiere.
            realDuration:
              type: Duration 
              description: Durata reale del cantiere, puó divergere da quella inserita alla creazione del cantiere.