swagger: '2.0'
info:
  version: '1.0'
  title: "PavedWay"
  description: PavedWay sono le API del sistema
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: polls.apiblueprint.org
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /events:
    x-summary: Events Collection
    get:
      summary: List All Events
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Events/id'

    post:
      description: >-
        You can create an event inserting the informations 
        that the events requires as: Id, nome, durata, upload date, data inizio presunta, data fine presunta, location, comments
      summary: Create a New Question
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/eventDisplay'
      responses:
        201:
          description: ''
          schema:
            $ref: '#/definitions/event'
definitions:
  Event:
    title: event
    type: object
    properties:
      Id:
        type: string
      nome:
        type: string
      durata:
        type: integer
        format: int32
      upload_date:
        type: timestamp
      data_inizio:
        type: date
      data_fine:
        type: date
      location:
        type: location
      comments:
        type: array
        items:
          $ref: '#/definitions/event'
    required:
      - Id
      - nome
      - durata
      - upload_date
      - data_inizio
      - data_fine
      - location
      - comments
  EventDisplay:
    title: event Display
    type: object
    properties:
      questioevent:
        type: object
    required:
      - event