openapi: 3.0.0

info:
  title: Paved Way API
  description: API per la gestione degli eventi sulla mobilità della città di Trento.
  version: 1.0.0

servers:
  - url: TODO

paths:
  /site:
    summary: Restituisce la lista dei cantieri esistenti.
    description: Restituisce la lista dei cantieri esistenti.
    parameters:
      - in: query
        name: limit
        schema:
          type: integer
        description: Numero massimo di cantieri da restituire.
    responses:
      "200":
        description: OK
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Sites"
      "500":
        description: Errore interno del server.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CommonError"
components:
  schemas:
    CommonError:
      type: object
      properties:
        error:
          type: string
          description: Messaggio di errore.
        code:
          type: integer
          description: Codice di errore.
        message:
          type: string
          description: Messaggio di errore dettagliato.

    Site:
      type: object
      properties:
        companyName: 
          type: string
          description: Nome della ditta di costruzioni che sta lavorando sul cantiere
        realDuration:
          type: Duration 
          description: Reale durata del cantiere, puó divergere da quella ipotetica definita su event

    Duration:
      type: object
      properties:
        start:
          type: string
          format: date-time
          description: Data e ora di inizio dell'evento.
        end:
          type: string
          format: date-time
          description: Data e ora di fine dell'evento.